/**
 * package-deploy.js
 *
 * Builds a self-contained bundle for deploying the test server onto a machine
 * that has Docker and nothing else - no git, no submodule, no Go toolchain, no
 * Node, and no registry access.
 *
 * Run: node scripts/package-deploy.js
 *
 * ── WHY A BUNDLE AND NOT "git clone on the server" ──────────────────────────
 *
 * The runbook's clone-and-build path needs git, the submodule, a Go build inside
 * Docker, and Node for the test assets. That is four things that can each be
 * missing or blocked on a hardened host, discovered one at a time over ssh.
 * Everything here is resolved on the machine that already works.
 *
 * ── HOW THE BUNDLE'S COMPOSE FILE DIFFERS ───────────────────────────────────
 *
 * The repository's compose builds backend-go from ./backend-go. The bundle has
 * no source, so its compose names the image instead. That file is GENERATED from
 * the repository one rather than kept beside it, so the two cannot drift: edit
 * docker-compose.backend-go.yml and re-run this.
 */

import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT_ROOT = path.join(ROOT, "deploy");
const STAGE = path.join(OUT_ROOT, "speedtest-deploy");

const BACKEND_IMAGE = "speedtest-backend-go:latest";
const NGINX_IMAGE = "nginx:1.27-alpine";

const log = (m) => console.log("\x1b[36m[package]\x1b[0m " + m);
const warn = (m) => console.log("\x1b[33m[package] WARN " + m + "\x1b[0m");
const ok = (m) => console.log("\x1b[32m[package] OK\x1b[0m " + m);

function sh(cmd, opts) {
  return execSync(cmd, { cwd: ROOT, stdio: "pipe", ...opts }).toString();
}

function copy(rel) {
  const to = path.join(STAGE, rel);
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(path.join(ROOT, rel), to);
}

function human(bytes) {
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(0) + " KB";
  return (bytes / 1024 / 1024).toFixed(1) + " MB";
}

/*
  Turn the repository compose into the bundle's: no build context, a named image
  instead. Everything else - profiles, ports, volumes, the environment contract -
  carries through untouched, which is the point of generating rather than
  maintaining a second copy.
*/
function bundleCompose() {
  /*
    Line endings are normalised before matching, and the bundle is written with
    LF. git checks this repository out with CRLF on Windows, which made the
    pattern below silently never match - the guard caught it, but only because
    it is there. The bundle targets Linux either way.
  */
  const src = fs
    .readFileSync(path.join(ROOT, "docker-compose.backend-go.yml"), "utf8")
    .replace(/\r\n/g, "\n");
  const built = src.replace(
    /    build:\n      context: \.\/backend-go\n/,
    "    # Loaded from images.tar by `docker load` - there is no source here to\n" +
      "    # build from. See DEPLOY.md.\n" +
      "    image: " +
      BACKEND_IMAGE +
      "\n"
  );
  if (built === src) {
    throw new Error(
      "could not find the backend-go build block in docker-compose.backend-go.yml - " +
        "the bundle would try to build from source it does not contain"
    );
  }
  return (
    "# GENERATED by scripts/package-deploy.js - do not edit here.\n" +
    "# Edit docker-compose.backend-go.yml in the repository and re-package.\n" +
    built
  );
}

function deployNotes(arch) {
  const B = "```";
  return [
    "# Deploy bundle",
    "",
    "Everything needed to run the test server on a machine that has Docker and",
    "nothing else. Generated by `scripts/package-deploy.js`.",
    "",
    "**The images are " + arch + ".** On a different architecture they will not run.",
    "Re-package on a matching machine, or build from source on the target.",
    "",
    "## 0 - Unpack",
    "",
    B + "sh",
    "tar -xf speedtest-deploy.tar",
    "cd speedtest-deploy",
    B,
    "",
    "If you are reading this you have already done it. It is written down because",
    "the outer archive is a bundle, not a Docker image: `docker load -i",
    "speedtest-deploy.tar` answers `unrecognized image format`, which is easy to",
    "read as a corrupt download rather than as the wrong file. The image archive",
    "is `images.tar`, one level in.",
    "",
    "## 1 - Load the images",
    "",
    B + "sh",
    "docker load -i images.tar",
    B,
    "",
    "Loads `" + BACKEND_IMAGE + "` and `" + NGINX_IMAGE + "`. No registry access is",
    "needed at any point.",
    "",
    "## 2 - Certificate",
    "",
    "The test server has to be https: the super-app WebView refuses http as mixed",
    "content, and the build refuses to package an http server list.",
    "",
    B + "sh",
    "sudo certbot certonly --standalone -d speedtest.example.la",
    B,
    "",
    "Mount the **live** directory below, not a copy - certbot renews in place, and",
    "a copy would keep serving the expired certificate until somebody noticed.",
    "",
    "## 3 - Configure",
    "",
    B + "sh",
    "export SPEEDTEST_STATISTICS_PASSWORD='<a real password>'",
    "export SPEEDTEST_SERVER_NAME='speedtest.example.la'",
    "export SPEEDTEST_CERT_DIR='/etc/letsencrypt/live/speedtest.example.la'",
    "export SPEEDTEST_ALLOWED_ORIGIN_REGEX='^https://app[.]unitel[.]com[.]la$'",
    B,
    "",
    "Write the dots as `[.]`, not `\\.`. Some shells rewrite the backslash on the",
    "way into docker and the regex then matches nothing - every origin refused,",
    "including the right one. It fails closed, but it costs an afternoon.",
    "",
    "Then edit `docker/nginx-speedtest-endpoints.conf` and replace",
    "`allow 10.0.0.0/8` with the operations network, or the statistics page stays",
    "closed to everybody.",
    "",
    "## 4 - Run",
    "",
    B + "sh",
    "docker compose --profile tls up -d",
    B,
    "",
    "`--profile dev` instead gives plain http on :8087, for checking the stack",
    "locally. Selecting neither profile starts the backend with nothing in front",
    "of it and publishes no port - inconvenient, and the safe way round.",
    "",
    "## 5 - Check it",
    "",
    "The full acceptance set is in `deploy-backend.md` section 6. The two that",
    "matter most: `garbage.php?ckSize=1` must return `200 1048576`, and an allowed",
    "origin must get **exactly one** `Access-Control-Allow-Origin` header - two",
    "makes the browser reject every response and every measurement fails.",
    "",
    "The first request after `up -d` can come back short while the container is",
    "still starting. Repeat it before believing it.",
    ""
  ].join("\n");
}

function main() {
  log("building the backend image...");
  sh("docker compose -f docker-compose.backend-go.yml build backend-go", {
    env: { ...process.env, SPEEDTEST_STATISTICS_PASSWORD: "packaging-placeholder" }
  });

  const arch = sh(
    "docker image inspect " + BACKEND_IMAGE + " --format {{.Os}}/{{.Architecture}}"
  ).trim();
  log("image platform: " + arch);

  fs.rmSync(OUT_ROOT, { recursive: true, force: true });
  fs.mkdirSync(STAGE, { recursive: true });

  /* Both images in one archive. The target may have no registry access at all,
     and nginx:alpine is as unreachable there as our own image. */
  log("saving images (the slow part)...");
  const imagesTar = path.join(STAGE, "images.tar");
  sh('docker save ' + BACKEND_IMAGE + " " + NGINX_IMAGE + ' -o "' + imagesTar + '"');
  ok("images.tar  " + human(fs.statSync(imagesTar).size));

  fs.writeFileSync(path.join(STAGE, "docker-compose.yml"), bundleCompose());

  for (const f of [
    "docker/nginx-backend-go.conf",
    "docker/nginx-backend-go-tls.conf",
    "docker/nginx-speedtest-endpoints.conf",
    "docker/speedtest_limits.conf",
    "docker/speedtest_proxy.conf",
    "docker/backend-go.settings.toml"
  ]) {
    copy(f);
  }

  /* 40 MB, and not optional: without it getIP returns no ISP name and
     MOBILE_OPERATOR - the carrier the whole report groups by - is null on every
     record. */
  copy("backend/country_asn.mmdb");
  copy("docs/deploy-backend.md");

  const assetsDir = path.join(ROOT, "test-assets");
  fs.mkdirSync(path.join(STAGE, "test-assets"), { recursive: true });
  const have = fs.existsSync(assetsDir) ? fs.readdirSync(assetsDir) : [];
  for (const f of have) {
    fs.copyFileSync(path.join(assetsDir, f), path.join(STAGE, "test-assets", f));
  }
  if (!have.includes("browse-sample.html")) {
    warn("test-assets/browse-sample.html missing - the Web stage will 404.");
    warn("  Run: node scripts/make-test-assets.js");
  }
  if (!have.includes("video-sample.mp4")) {
    warn("test-assets/video-sample.mp4 missing - the Video stage will 404 and report Error.");
    warn("  It needs ffmpeg; scripts/make-test-assets.js prints the command.");
  }

  fs.writeFileSync(path.join(STAGE, "DEPLOY.md"), deployNotes(arch));

  log("archiving...");
  const archive = path.join(OUT_ROOT, "speedtest-deploy.tar");
  /*
    Not gzipped. The bulk of the bundle is images.tar, whose layers are already
    compressed, so a second pass buys little for the time it costs - and a plain
    .tar is what the extension says it is.

    Relative paths, run from inside the output directory: GNU tar reads a
    leading "C:" in a Windows path as a remote host and fails to resolve it.
  */
  sh("tar -cf speedtest-deploy.tar speedtest-deploy", { cwd: OUT_ROOT });
  ok("bundle: " + path.relative(ROOT, archive) + "  " + human(fs.statSync(archive).size));

  /*
    The same three commands, OUTSIDE the archive.

    DEPLOY.md only becomes readable after unpacking, which is exactly the step
    somebody has not taken yet when they reach for `docker load -i
    speedtest-deploy.tar` - and Docker answers that with "unrecognized image
    format", which reads like a corrupt transfer rather than the wrong file.
    Send this file alongside the archive.
  */
  fs.writeFileSync(
    path.join(OUT_ROOT, "README-FIRST.txt"),
    [
      "speedtest-deploy.tar is a BUNDLE, not a Docker image.",
      "",
      "  tar -xf speedtest-deploy.tar",
      "  cd speedtest-deploy",
      "  docker load -i images.tar        <- the image archive is this one, inside",
      "",
      "Then follow DEPLOY.md in that directory.",
      "",
      "Running `docker load -i speedtest-deploy.tar` on the bundle itself answers",
      '"unrecognized image format". That means wrong file, not corrupt download.',
      ""
    ].join("\n")
  );

  console.log(
    "\nCopy it over, then on the server:\n" +
      "  tar -xf speedtest-deploy.tar && cd speedtest-deploy\n" +
      "  docker load -i images.tar\n" +
      "  # then follow DEPLOY.md\n"
  );
}

main();
